version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=root08
      - DB_NAME=restaurant_menu

  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root08
      - MYSQL_DATABASE=restaurant_menu
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local